#!/bin/sh

for mac in $(ls /lib/gluon/treatment/macs); do
	yes=$(ifconfig br-client | grep $mac|wc -l)
	if [ $yes != 0 ]; then
		/lib/gluon/treatment/macs/$mac
	fi
        rm /lib/gluon/treatment/macs/$mac
done

# try opkg remove 
opkg remove gluon-treatment
# delete cronjob manually - if opkg wont work
rm /usr/lib/micron.d/treatment
# delete script and mac treatments itself
rm /lib/gluon/treatment -rf
